### ISSUE TITLE
Github リポジトリのインポート

### ISSUE THREAD

**Issue by irixjp** [infra-ci-book/gitlab-vagrant-ansible#3]
自動でできないか確かめる。

**Comment by spchildren** [comment]
この作業を自動化すると、読者がGitLab上で何が行われているのか理解しづらいので、画面操作で一度だけImport作業やってもらうほうが理解しやすいと思うのですがいかがでしょー？

**Comment by irixjp** [comment]
あ、たしかにそうですね！
そうしましょうか！

3章の環境構築の流れの一番最後で説明がいですかね。
