### ISSUE TITLE
Install GitLab Runner タスクで失敗する

### ISSUE THREAD

**Issue by morinokami** [infra-ci-book/gitlab-vagrant-ansible#5]
書籍の3.5.4にもとづき本リポジトリをクローンし、`ansible-playbook site.yml`を実行すると、`Install GitLab Runner`において失敗するようです。原因としては、`Package gitlab-runner-10.5.0-1.x86_64.rpm is not signed`ということのようです。ひとまずの回避策として、`Install GitLab Runner`の`yum`モジュール使用箇所において`disable_gpg_check: yes`とすることでタスクを続行することはできましたが、他の読者がここで引っ掛かることがないように、issueとして挙げておきます。

**Comment by irixjp** [comment]
時間が立ってしまい申し訳ございません。
ご指摘ありがとうございました。

5d2cb29 にて修正いたしました。
